version: '3.0'
services:
  web:
    container_name: client_datanalyst
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - client
  server:
    container_name: backend_datanalyst
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server:/code
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - client
      - server_db
  db:
    container_name: db_datanalyst
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - server_db
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_datanalyst
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
    networks:
      - server_db
networks:
  client:
    driver: bridge
  server_db:
    driver: bridge